### ISSUE TITLE
Pivotal Webhook fails on update

### ISSUE THREAD

**Issue by nrodriguez** [xogroup/pivotal-status-check#8]
```bash
52.88.182.158, 10.189.181.242 - - [01/Mar/2017:15:31:36 +0000] "POST /accepted HTTP/1.1" 500 209367 0.1165
/usr/local/bundle/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/div.rb:1: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/fdiv.rb:1: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/backports-3.6.8/lib/backports/2.1.0/bignum/bit_length.rb:1: warning: constant ::Bignum is deprecated
/usr/local/bundle/gems/backports-3.6.8/lib/backports/2.1.0/fixnum/bit_length.rb:1: warning: constant ::Fixnum is deprecated
2017-03-01 15:31:47 - ArgumentError - wrong number of arguments (given 1, expected 0):
	/app/app/models/github_client.rb:24:in `find_branch'
	/app/app/controllers/pivotal_statuses_controller.rb:19:in `block in <class:PivotalStatusesController>'
```

**Comment by nrodriguez** [comment]
Fixed in #9
